RBE 2000 level template code: RobotControlCenter Class Reference
RobotControlCenter Class Reference
#include <RobotControlCenter.h>
Public Member Functions
RobotControlCenter (String *name)
~RobotControlCenter ()
void loop ()
Data Fields
StudentsRobot * robot
Protected Member Functions
void setup ()
void fastLoop ()
Protected Attributes
HBridgeEncoderPIDMotor motor1
HBridgeEncoderPIDMotor motor2
HBridgeEncoderPIDMotor motor3
Servo servo
Private Member Functions
void setupPIDServers ()
Private Attributes
int64_t lastPrint = 0
String * name
PIDMotor * pidList [numberOfPID]
UDPSimplePacket coms
WifiManager manager
state_t state = Startup
GetIMU * sensor
IRCamSimplePacketComsServer * serverIR
Detailed Description
RobotControlCenter is the main class for the 2000 level student code
This class is the starting point for all the code. Student code is housed in StudentsRobot class
See also
StudentsRobot
This class managed the overall state machine for dealing with connecting and maintaining connection to the WiFi, constructing the StudentsRobot class, and managing the StudentsRobot calls to updates its state machine as well as its PID loops.
Definition at line 59 of file RobotControlCenter.h.
Constructor & Destructor Documentation
RobotControlCenter::RobotControlCenter (String * name)
RobotControlCenter constructor
The name is used by the SimplePacketComs stack to locate your specific robot on the network.
Definition at line 60 of file RobotControlCenter.cpp.
References motor1, motor2, motor3, name, pidList, robot, sensor, serverIR, Startup, and state.
RobotControlCenter::~RobotControlCenter () inline
Definition at line 96 of file RobotControlCenter.h.
References loop().
Member Function Documentation
void RobotControlCenter::fastLoop () protected
The fast loop actions
This should be run every loop and is internally gated for fast opperation
See also
StudentsRobot::Approve
StudentsRobot::ClearFaults
StudentsRobot::EStop
StudentsRobot::PickOrder
Definition at line 142 of file RobotControlCenter.cpp.
References coms, manager, StudentsRobot::pidLoop(), robot, Startup, state, and StudentsRobot::updateStateMachine().
Referenced by loop().
void RobotControlCenter::loop ()
Pulse the loop function from the main thread
This function is callled over and over by the INO loop()
Definition at line 18 of file RobotControlCenter.cpp.
References fastLoop(), lastPrint, IRCamSimplePacketComsServer::loop(), GetIMU::loop(), manager, readIMU, readIR, sensor, serverIR, setup(), Startup, state, and WaitForConnect.
Referenced by loop(), and ~RobotControlCenter().
void RobotControlCenter::setup () protected
Internal setup function to set up all objects
This function is called as part of the state machine by the object
Definition at line 72 of file RobotControlCenter.cpp.
References HBridgeEncoderPIDMotor::attach(), bno, coms, HBridgeEncoderPIDMotor::getPosition(), manager, motor1, MOTOR1_DIR, MOTOR1_ENCA, MOTOR1_ENCB, MOTOR1_PWM, motor2, MOTOR2_DIR, MOTOR2_ENCA, MOTOR2_ENCB, MOTOR2_PWM, motor3, MOTOR3_DIR, MOTOR3_ENCA, MOTOR3_ENCB, MOTOR3_PWM, myDFRobotIRPosition, name, numberOfPID, pidList, robot, sensor, serverIR, servo, SERVO_PIN, PIDMotor::setSetpoint(), GetIMU::startSensor(), Startup, state, and WaitForConnect.
Referenced by loop().
void RobotControlCenter::setupPIDServers () private
Field Documentation
UDPSimplePacket RobotControlCenter::coms private
Definition at line 71 of file RobotControlCenter.h.
Referenced by fastLoop(), and setup().
int64_t RobotControlCenter::lastPrint = 0 private
Definition at line 63 of file RobotControlCenter.h.
Referenced by loop().
WifiManager RobotControlCenter::manager private
Definition at line 73 of file RobotControlCenter.h.
Referenced by fastLoop(), loop(), and setup().
HBridgeEncoderPIDMotor RobotControlCenter::motor1 protected
Definition at line 112 of file RobotControlCenter.h.
Referenced by RobotControlCenter(), and setup().
HBridgeEncoderPIDMotor RobotControlCenter::motor2 protected
Definition at line 113 of file RobotControlCenter.h.
Referenced by RobotControlCenter(), and setup().
HBridgeEncoderPIDMotor RobotControlCenter::motor3 protected
Definition at line 114 of file RobotControlCenter.h.
Referenced by RobotControlCenter(), and setup().
String* RobotControlCenter::name private
Definition at line 65 of file RobotControlCenter.h.
Referenced by RobotControlCenter(), and setup().
PIDMotor* RobotControlCenter::pidList[numberOfPID] private
Definition at line 67 of file RobotControlCenter.h.
Referenced by RobotControlCenter(), and setup().
StudentsRobot* RobotControlCenter::robot
A pointer to the students robot
NULL at startup, this is instantiated by the RobotControlCenter state machine. This variable is set as part of
See also
RobotControlCenter::setup
Definition at line 110 of file RobotControlCenter.h.
Referenced by fastLoop(), RobotControlCenter(), and setup().
GetIMU* RobotControlCenter::sensor private
Definition at line 83 of file RobotControlCenter.h.
Referenced by loop(), RobotControlCenter(), and setup().
IRCamSimplePacketComsServer* RobotControlCenter::serverIR private
Definition at line 85 of file RobotControlCenter.h.
Referenced by loop(), RobotControlCenter(), and setup().
Servo RobotControlCenter::servo protected
Definition at line 116 of file RobotControlCenter.h.
Referenced by setup().
state_t RobotControlCenter::state = Startup private
Definition at line 80 of file RobotControlCenter.h.
Referenced by fastLoop(), loop(), RobotControlCenter(), and setup().
The documentation for this class was generated from the following files:
src/RobotControlCenter.h
src/RobotControlCenter.cpp