RBE 2000 level template code: GetIMU Class Reference
GetIMU Class Reference
#include <GetIMU.h>
Public Member Functions
GetIMU ()
void event (float *buffer)
void loop ()
void startSensor (Adafruit_BNO055 *_bno)
void print ()
float getLINEARACCEL_X ()
float getLINEARACCEL_Y ()
float getLINEARACCEL_Z ()
float getGYROSCOPE_X ()
float getGYROSCOPE_Y ()
float getGYROSCOPE_Z ()
float getGRAVITY_X ()
float getGRAVITY_Y ()
float getGRAVITY_Z ()
float getEULER_azimuth ()
float getEULER_elevation ()
float getEULER_tilt ()
void setXPosition (float x)
void setYPosition (float y)
void setZPosition (float z)
Private Attributes
Adafruit_BNO055 * bno
volatile float bufferINTERNAL [NUM_IMU_VALUES]
bool started
int updateIndex =0
Detailed Description
Definition at line 18 of file GetIMU.h.
Constructor & Destructor Documentation
GetIMU::GetIMU () inline
Definition at line 30 of file GetIMU.h.
References event(), getEULER_azimuth(), getEULER_elevation(), getEULER_tilt(), getGRAVITY_X(), getGRAVITY_Y(), getGRAVITY_Z(), getGYROSCOPE_X(), getGYROSCOPE_Y(), getGYROSCOPE_Z(), getLINEARACCEL_X(), getLINEARACCEL_Y(), getLINEARACCEL_Z(), loop(), print(), setXPosition(), setYPosition(), setZPosition(), and startSensor().
Member Function Documentation
void GetIMU::event (float * buffer)
Definition at line 13 of file GetIMU.cpp.
References bufferINTERNAL, NUM_IMU_VALUES, and started.
Referenced by GetIMU().
float GetIMU::getEULER_azimuth ()
Definition at line 94 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getEULER_elevation ()
Definition at line 97 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getEULER_tilt ()
Definition at line 100 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGRAVITY_X ()
Definition at line 85 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGRAVITY_Y ()
Definition at line 88 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGRAVITY_Z ()
Definition at line 91 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGYROSCOPE_X ()
Definition at line 76 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGYROSCOPE_Y ()
Definition at line 79 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getGYROSCOPE_Z ()
Definition at line 82 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getLINEARACCEL_X ()
Definition at line 67 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getLINEARACCEL_Y ()
Definition at line 70 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
float GetIMU::getLINEARACCEL_Z ()
Definition at line 73 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU().
void GetIMU::loop ()
Definition at line 21 of file GetIMU.cpp.
References bno, bufferINTERNAL, started, and updateIndex.
Referenced by GetIMU(), and RobotControlCenter::loop().
void GetIMU::print ()
Definition at line 111 of file GetIMU.cpp.
References bufferINTERNAL, and started.
Referenced by GetIMU(), and StudentsRobot::updateStateMachine().
void GetIMU::setXPosition (float x)
Definition at line 58 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU(), and StudentsRobot::StudentsRobot().
void GetIMU::setYPosition (float y)
Definition at line 61 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU(), and StudentsRobot::StudentsRobot().
void GetIMU::setZPosition (float z)
Definition at line 64 of file GetIMU.cpp.
References bufferINTERNAL.
Referenced by GetIMU(), and StudentsRobot::StudentsRobot().
void GetIMU::startSensor (Adafruit_BNO055 * _bno)
Definition at line 104 of file GetIMU.cpp.
References bno, and started.
Referenced by GetIMU(), and RobotControlCenter::setup().
Field Documentation
Adafruit_BNO055* GetIMU::bno private
Definition at line 20 of file GetIMU.h.
Referenced by loop(), and startSensor().
volatile float GetIMU::bufferINTERNAL[NUM_IMU_VALUES] private
Definition at line 25 of file GetIMU.h.
Referenced by event(), getEULER_azimuth(), getEULER_elevation(), getEULER_tilt(), getGRAVITY_X(), getGRAVITY_Y(), getGRAVITY_Z(), getGYROSCOPE_X(), getGYROSCOPE_Y(), getGYROSCOPE_Z(), getLINEARACCEL_X(), getLINEARACCEL_Y(), getLINEARACCEL_Z(), loop(), print(), setXPosition(), setYPosition(), and setZPosition().
bool GetIMU::started private
Definition at line 26 of file GetIMU.h.
Referenced by event(), loop(), print(), and startSensor().
int GetIMU::updateIndex =0 private
Definition at line 27 of file GetIMU.h.
Referenced by loop().
The documentation for this class was generated from the following files:
src/commands/GetIMU.h
src/commands/GetIMU.cpp